import type { Engine } from "@babylonjs/core/Engines/engine";
import type { LaboratoryApi } from "../scene/createScene";
import { FRAMEWORK_VERSION, MAP_FORMAT_VERSION } from "../core/version";

export type RendererName = "WebGL2" | "WebGL";

export function getRendererName(engine: Engine): RendererName {
  return engine.webGLVersion >= 2 ? "WebGL2" : "WebGL";
}

export function updateDebugReadout(engine: Engine, laboratory: LaboratoryApi, mobile: boolean): void {
  const canvas = engine.getRenderingCanvas();
  const telemetry = laboratory.telemetry();
  const city = laboratory.cityStats();
  const interaction = laboratory.interactionDebug();
  const interior = laboratory.interiorDebug();
  const semantic = laboratory.semanticDebug();
  const world = laboratory.worldStatistics();
  const mission = laboratory.missionDebug();
  const guide = laboratory.missionGuideDebug();
  const characters = laboratory.characterDebug();
  const navigation = laboratory.navigationDebug();
  const map = laboratory.mapState();
  const visual = laboratory.visualState();
  setText("renderer-value", getRendererName(engine));
  setText("framework-version-value", FRAMEWORK_VERSION);
  setText("map-format-version-value", String(MAP_FORMAT_VERSION));
  setText("canvas-value", canvas ? `${canvas.width} × ${canvas.height}` : "0 × 0");
  setText("viewport-value", `${Math.round(window.visualViewport?.width ?? window.innerWidth)} × ${Math.round(window.visualViewport?.height ?? window.innerHeight)}`);
  setText("device-value", mobile ? "Mobile" : "Desktop");
  setText("fps-value", String(Math.round(engine.getFps())));
  setText("mesh-value", String(laboratory.objectCount()));
  setText("active-mesh-value", String(visual.activeMeshes));
  setText("visual-environment-value", visual.environment);
  setText("visual-quality-value", `${visual.quality} (${visual.resolvedQuality})`);
  setText("visual-fog-value", visual.fog);
  setText("visual-shadow-value", visual.shadow ? "ON" : "OFF");
  setText("visual-lod-value", `LEVEL ${visual.lod}`);
  setText("active-lights-value", String(visual.activeLights));
  setText("material-count-value", String(visual.materials));
  setText("shadow-caster-value", String(visual.shadowCasters));
  setText("camera-value", `${telemetry.x.toFixed(1)} / ${telemetry.y.toFixed(1)} / ${telemetry.z.toFixed(1)}`);
  setText("map-mode-value", map.mode);
  setText("map-seed-value", String(map.worldSeed));
  setText("current-chunk-value", `${map.currentChunk.x},${map.currentChunk.z}`);
  setText("loaded-chunks-value", String(map.loadedChunks.length));
  setText("total-chunks-value", String(map.totalChunks));
  setText("auto-expansion-value", map.autoExpansion ? "ON" : "OFF");
  setText("chunk-unload-value", map.chunkUnload ? "ON" : "OFF");
  setText("city-seed-value", city ? String(city.seed) : "—");
  setText("building-count-value", city ? String(city.buildingCount) : "0");
  setText("road-count-value", city ? String(city.roadCount) : "0");
  setText("city-object-count-value", city ? String(city.objectCount) : "0");
  setText("generation-time-value", city ? `${city.generationTime.toFixed(1)} ms` : "—");
  setText("city-style-value", city?.styleLabel ?? "—");
  setText("interpretation-value", city?.interpretation ?? "—");
  setText("focus-value", interaction?.id ?? "—");
  setText("interaction-type-value", interaction?.type ?? "—");
  setText("interaction-distance-value", interaction ? `${interaction.distance.toFixed(2)} m` : "—");
  setText("current-area-value", semantic.area?.id ?? "—");
  setText("current-area-type-value", semantic.area?.type ?? "—");
  setText("current-area-tags-value", semantic.area?.tags.join(", ") || "—");
  setText("current-building-value", semantic.building ?? interior?.building ?? "—");
  setText("current-floor-value", semantic.floor ? String(semantic.floor) : interior ? String(interior.floor) : "—");
  setText("current-room-value", semantic.room ?? interior?.room ?? "—");
  setText("world-road-value", String(world.roads));
  setText("world-building-value", String(world.buildings));
  setText("world-room-value", String(world.rooms));
  setText("world-dead-end-value", String(world.deadEnds));
  setText("world-safe-value", String(world.safeAreas));
  setText("world-danger-value", String(world.dangerAreas));
  setText("enemy-spawn-value", String(world.enemySpawns));
  setText("npc-spawn-value", String(world.npcSpawns));
  setText("mission-seed-value", String(mission.plan.seed));
  setText("mission-type-value", mission.plan.type);
  setText("mission-difficulty-value", mission.plan.difficulty);
  setText("mission-total-value", String(mission.plan.steps.length));
  setText("mission-current-value", mission.state.current?.id ?? "COMPLETE");
  setText("mission-retry-value", String(mission.plan.retryCount));
  setText("mission-valid-value", mission.validation.valid ? "PASS" : "FAIL");
  setText("guide-objective-value", guide.objectiveId);
  setText("guide-target-value", guide.targetId);
  setText("guide-type-value", guide.targetType);
  setText("guide-distance-value", guide.status === "READY" ? `${guide.distance.toFixed(1)}m` : "—");
  setText("guide-height-value", guide.status === "READY" ? `${guide.heightDiff >= 0 ? "+" : ""}${guide.heightDiff.toFixed(1)}m` : "—");
  setText("guide-visible-value", guide.visible ? "YES" : "NO");
  setText("guide-screen-value", guide.onScreen ? "YES" : "NO");
  setText("guide-status-value", guide.status);
  setText("npc-count-value", String(characters.npcCount));
  setText("enemy-count-value", String(characters.enemyCount));
  setText("selected-character-value", characters.selected?.id ?? "—");
  setText("character-state-value", characters.selected?.state ?? "—");
  setText("character-target-value", characters.selected?.target ?? "—");
  setText("character-area-value", characters.selected?.area ?? "—");
  setText("enemy-ai-value", characters.enemyAI ? "ON" : "OFF");
  setText("navigation-status-value", navigation.status);
  setText("navigation-mode-value", navigation.mode);
  setText("navigation-error-value", navigation.error || "—");
  setText("navigation-stack-value", navigation.stack || "—");
  setText("navigation-target-mesh-value", String(navigation.targetMeshCount));
  setText("navigation-walkable-mesh-value", String(navigation.walkableMeshCount));
  setText("navigation-obstacle-mesh-value", String(navigation.obstacleMeshCount));
  setText("navigation-parameters-value", navigation.buildParameters);
  setText("navmesh-triangles-value", String(navigation.triangles));
  setText("navmesh-build-time-value", `${navigation.buildTime.toFixed(1)} ms`);
  setText("navigation-validation-value", navigation.validation);
  setText("path-failures-value", String(navigation.pathFailures));
  setText("nav-start-area-value", characters.selected?.startArea ?? "—");
  setText("nav-target-area-value", characters.selected?.targetArea ?? "—");
  setText("nav-path-length-value", characters.selected ? `${characters.selected.pathLength.toFixed(1)} m` : "—");
  setText("nav-waypoint-count-value", String(characters.selected?.waypointCount ?? 0));
  setText("nav-current-waypoint-value", String(characters.selected?.currentWaypoint ?? 0));
  setText("nav-repath-value", characters.selected ? `${Math.max(0, characters.selected.repathTimer).toFixed(2)} s` : "—");
  setText("stuck-count-value", String(characters.selected?.stuckCount ?? 0));
  setText("last-stuck-value", characters.selected?.lastStuckPosition ?? "—");
}

function setText(id: string, value: string): void {
  const element = document.getElementById(id);
  if (element) element.textContent = value;
}
